name: firebaseflutterlogin
description: Flutter Project Sign in and Signup
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Ruda
      fonts:
        - asset: assets/fonts/Ruda-VariableFont_wght.ttf
        - asset: assets/fonts/Ruda-Black.ttf
        - asset: assets/fonts/Ruda-Bold.ttf
        - asset: assets/fonts/Ruda-ExtraBold.ttf
        - asset: assets/fonts/Ruda-Medium.ttf
          style: italic
    - family: Ruda-SemiBold
      fonts:
        - asset: assets/fonts/Ruda-SemiBold.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
    - family: Ruda-Regular
      fonts:
        - asset: assets/fonts/Ruda-Regular.ttf
          weight: 700
